# Generated by Django 6.0.4 on 2026-05-04 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('unidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: OBS, UCI, UTI', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('piso', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('tipo_atencion', models.CharField(help_text='Urgencia o Electiva', max_length=50)),
                ('cantidad_pacientes', models.IntegerField()),
                ('dias_espera_promedio', models.IntegerField()),
                ('fecha_corte', models.DateField()),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_espera', to='dashboard.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cama', models.CharField(help_text='Ej: CAMA-201', max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Bloqueada', 'Bloqueada'), ('Limpieza', 'Limpieza')], max_length=50)),
                ('nivel_cuidado', models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=20, null=True)),
                ('paciente_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('paciente_edad', models.IntegerField(blank=True, null=True)),
                ('paciente_peso', models.FloatField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camas', to='dashboard.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='GestionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('peso_grd', models.FloatField()),
                ('inliers_pct', models.FloatField()),
                ('outliers_pct', models.FloatField()),
                ('mortalidad_pct', models.FloatField()),
                ('estancias_evitables', models.IntegerField()),
                ('total_egresos', models.IntegerField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestion_clinica', to='dashboard.servicio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('servicio', 'anio', 'mes'), name='idx_unico_gestion_clinica')],
            },
        ),
        migrations.CreateModel(
            name='ValorIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2025)),
                ('mes', models.IntegerField(help_text='0 = Anual, 1 al 12 = Meses exactos')),
                ('valor_calculado', models.FloatField()),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='dashboard.indicador')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_indicadores', to='dashboard.servicio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('servicio', 'indicador', 'anio', 'mes'), name='idx_unico_valor_calculado')],
            },
        ),
    ]
