# Generated by Django 6.0.4 on 2026-05-11 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(default='General', max_length=100)),
                ('color', models.CharField(default='primary', max_length=50)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('altas', models.IntegerField(default=0)),
                ('traslados', models.IntegerField(default=0)),
                ('fallecidos', models.IntegerField(default=0)),
                ('dias_cama_disponibles', models.IntegerField(default=0)),
                ('dias_cama_ocupados', models.IntegerField(default=0)),
                ('dias_estada', models.IntegerField(default=0)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos', to='dashboard.nivel')),
            ],
            options={
                'ordering': ['nivel', 'mes'],
                'unique_together': {('nivel', 'mes')},
            },
        ),
    ]
