# Generated by Django 6.0.4 on 2026-05-11 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_nivel_egreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='OportunidadHospitalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('p1', models.IntegerField()),
                ('p2', models.IntegerField()),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oportunidad_hospitalizacion', to='dashboard.servicio')),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ServicioGrd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2025)),
                ('egresos', models.IntegerField(default=0)),
                ('pct_egresos', models.FloatField(default=0)),
                ('peso_grd', models.FloatField(default=0)),
                ('inliers_pct', models.FloatField(default=0)),
                ('outliers_pct', models.FloatField(default=0)),
                ('mortalidad_pct', models.FloatField(default=0)),
                ('estada_media', models.FloatField(default=0)),
                ('em_norma', models.FloatField(default=0)),
                ('estada_inliers', models.FloatField(default=0)),
                ('emaf_inlier', models.FloatField(default=0)),
                ('emac_inlier', models.FloatField(default=0)),
                ('iema_inlier', models.FloatField(default=0)),
                ('if_inlier', models.FloatField(default=0)),
                ('ic_inlier', models.FloatField(default=0)),
                ('estancias_evitables', models.FloatField(default=0)),
                ('estada_outliers', models.FloatField(default=0)),
                ('outliers_stay_pct', models.FloatField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grd_indicadores', to='dashboard.servicio')),
            ],
            options={
                'unique_together': {('servicio', 'anio')},
            },
        ),
    ]
